version: "3.8"
services: 
  lit-image:
    build: ./
    container_name: lit-container
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
      - /app/node_modules
  node-image:
    build: ./backend
    container_name: node-container
    ports:
      - '3000:3000'
    volumes: 
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - lit-image